### ISSUE TITLE
Camera: app passed NULL surface

### ISSUE THREAD

**Issue by TonyTangAndroid** [nisrulz/qreader#28] opened 2016-12-12 16:40 UTC
_Camera: app passed NULL surface_ on Android Nougat Google Pixel in Log Console.
There is no more message provided.

**Comment by nisrulz** [comment] 2016-12-12 17:59
@TonyTangAndroid are you setting the surface view as explained in the readme ? Also check if the sample app also throws the same error ?

**Comment by TonyTangAndroid** [comment] 2016-12-13 16:29
Yes. I was using the exact sample app that gets this error.

**Comment by joelclaudio** [comment] 2016-12-13 19:05
@nisrulz +1 I am having the same issue. It occurs when I read a QRCode with a video a url, launch the intent to play the video and come back to the fragment that has the qrreader. Using Lollipop on Moto G 1st gen.

**Comment by nisrulz** [comment] 2016-12-15 09:46
Let me look into it and update it here.

**Comment by pottiepie** [comment] 2016-12-26 07:31
@nisrulz I might be having the same issue. The surface view turns black and doesn't update whenever the activity resumes. This happens with the sample app as well.

To replicate, simply leave the app by going to home, then resume the app.

**Comment by malti4** [comment] 2017-01-05 08:52
Hello sir ,i have the same issue as of Mr Joelclaudio.And i really need the solution.Please help.When i open the mail client by intent than on coming back to activity i m not able to scan and surface view shows black screen.Please help as soon as possible

**Comment by pottiepie** [comment] 2017-01-05 12:11
Ok I managed to find the problem and fix it.

When `QReader.initAndStart()` is called in `onResume()`, it adds a `GlobalLayoutListener` on `surfaceView` which calls `QReader.start()`. In here, it checks the boolean `surfaceCreated` and if it is false, it adds `surfaceHolderCallback` to the holder.

Now the issue is that `surfaceHolderCallback` removes itself from `surfaceView` when it is destroyed. It might be a change in the latest Android but when the view is rebuilt, the same surfaceView is used and re-created. The problem is that the re-adding of `surfaceHolderCallback` occurs after the surfaceView has been created, thus the `surfaceCreated` listener event is never called, resulting in the camera not starting.

The way to fix this is to not remove the callback when `surfaceView` is destroyed. This can be done by removing line 106 of `QReader.java`: `surfaceHolder.removeCallback(this);`

**Comment by malti4** [comment] 2017-01-10 10:48
Helo sir,
Thank you for your precious reply.but m not able to identify line 106!!
where can i add "QReader.java: surfaceHolder.removeCallback(this);" .

**Comment by malti4** [comment] 2017-01-10 10:55
I got the line bt its the read only file ,so cant remove the line

**Comment by pottiepie** [comment] 2017-01-10 14:25
It is read only because you are currently "linking" to the package in GitHub. What you need to do is clone the source out and then add it as a module to your project. Then you can edit the source.

**Comment by nisrulz** [comment] 2017-01-10 18:10
@pottiepie if you think that you have fixed the issue, could you send a PR. I haven't been able to pick   the library code for sometime because of work.

**Comment by malti4** [comment] 2017-01-11 05:08
@pottiepie  i did as per your instructions bt it gives me error on resuming that "Fail to connect to camera service".So help me in that

**Comment by nisrulz** [comment] 2021-10-22 00:14
Closing as issue is outdated. Please open a new issue if the issue still persists.

The library will be undergoing some maintenance soon.

**Closed by nisrulz** 2021-10-22 00:14 UTC
