### ISSUE TITLE
Google Play Services Conflict

### ISSUE THREAD

**Issue by alon80** [nisrulz/qreader#21] opened 2016-07-18 09:17 UTC
Issue occurred after including Google Firebase in my project 

> java.lang.NoSuchMethodError: No static method zzC(Ljava/lang/Object;)Lcom/google/android/gms/dynamic/zzd; in class Lcom/google/android/gms/dynamic/zze; or its super classes (declaration of 'com.google.android.gms.dynamic.zze' appears in /data/app/com.remoteapps.vs-2/base.apk)
>                                                                         at com.google.android.gms.vision.barcode.internal.client.zzd$zza.zzb(Unknown Source)
>                                                                         at com.google.android.gms.vision.barcode.internal.client.zzd$zza.zza(Unknown Source)
>                                                                         at com.google.android.gms.vision.barcode.internal.client.zzd.zzIg(Unknown Source)
>                                                                         at com.google.android.gms.vision.barcode.internal.client.zzd.<init>(Unknown Source)
>                                                                         at com.google.android.gms.vision.barcode.BarcodeDetector$Builder.build(Unknown Source)
>                                                                         at github.nisrulz.qreader.QREader.init(QREader.java:82)

**Comment by nisrulz** [comment] 2016-07-18 09:23
@alon80 I am working on that. Should get solved in the next release. Give me until next weekend.

This is happening because the required transitive files `com.remoteapps.vs-2/base.apk` which are downloaded by google play services to facilitate Mobile Vision are not downloaded. It is should not be a conflict because of including Firebase in your project. 

Can you confirm that if you remove Firebase this works or doesnot work. Also what happens if you add Firebase back in.

Thank you

**Comment by alon80** [comment] 2016-07-18 10:47
@nisrulz Thanks for your reply.

The problem only occurs when adding Firebase - tried to remove/add several time so I am sure it is the Firebase includes that causes this error.

**Comment by nisrulz** [comment] 2016-07-18 11:06
@alon80 thanks for confirming. 

I will look into it and test it. Should get solved soon.

**Comment by mikorobyo** [comment] 2016-09-05 08:00
Hi @nisrulz, any idea why this problem occurs when the Firebase library is added? I just encountered the same issue. Thanks.

@alon80 Did you manage to find a solution? Thanks.

**Comment by nisrulz** [comment] 2016-09-05 08:03
@mikorobyo I haven't been able to pick this project up for some time. If someone else wants to go ahead and do that it would be great. I am however committed to solving issues arising in this project and would possibly try to fix it soon. 

Apologies for the inconvenience caused. I am a bit tied up with work.

**Comment by amineMpdam** [comment] 2016-09-21 13:14
Is this issue still open ??
Because i am facing the same problem with the 1.0.6 release.
After i added the dependency :  compile 'com.google.firebase:firebase-messaging:9.4.0' i started getting this build error "Multiple dex files define Lcom/google/android/gms/actions/ItemListIntents;"

**Comment by Alhima** [comment] 2016-10-19 13:10
Hi, I noticed this issue is still open, and one of my Seniors found a solution to this problem, so here it is in case that someone need a temporal solution:

The problem is between dependencies with Firebase and Qreader, so excluding the 'com.google.android.gms' group on the compile, and adding the compile for the Google vision library, worked for me. So, basically(in the module gradle):

compile ('com.github.nisrulz:qreader:1.0.6'){
        exclude group: 'com.google.android.gms'
    }
compile 'com.google.android.gms:play-services-vision:9.0.1'

Notice that the vision version(9.0.1) should be the same that all your play services.

Hope this fix some headaches!

Regards!

**Comment by nisrulz** [comment] 2016-11-28 19:24
Updated the library to v2.0, with a lot of fixes and API cleanup. Please give it a try and let me know if this issue was fixed.

Thank you

**Comment by amineMpdam** [comment] 2016-11-28 20:50
I'll give it a try.
Ps: thank you for a great library.

Le 28 nov. 2016 20:24, "Nishant Srivastava" <notifications@github.com> a
écrit :

**Comment by frog1014** [comment] 2017-01-06 12:49
I met the same issue with v2.0.1.

**Closed** 2017-06-29 14:41 UTC
Labels: help wanted
