### ISSUE TITLE
Barcode recognition libs are not downloaded and are not operational

### ISSUE THREAD

**Issue by RobertoLayna** [nisrulz/qreader#63] opened 2019-02-07 20:01 UTC
E/BarcodeNativeHandle: Error creating remote native handle
    com.google.android.gms.dynamite.DynamiteModule$zzc: No acceptable module found. Local version is 0 and remote version is 0.

...

E/QREader: Barcode recognition libs are not downloaded and are not operational

A week ago it worked correctly, but now it throws me that error.
I have updated Play services and even then it is not possible to open the scanner

Library works fine in Huawei P20 and Moto G6 Play

+ **Device Information:**  Moto E5 Play

+ **Android Version:**  8.1.0

**Comment by perusudroid** [comment] 2019-04-25 12:41
Please let know any solution for this. Unable to get camera preview using ML-Kit. 

Error Loading module
    com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.

W/BarcodeNativeHandle: Native handle not yet available. Reverting to no-op handle.

Library works fine in all other device except the following one

Device Information: Studio Mega Phone

Android Version: 8.1.0

**Comment by ShiftDigitalSolutions** [comment] 2019-09-30 18:34
The problem is that : this library needs more than 500 m free.

**Comment by trix0** [comment] 2020-11-20 10:25
I have the same issue. Any idea how to fix this?

**Comment by nisrulz** [comment] 2020-11-20 22:14
@trix0 this library is outdated. It still uses old google play libs which are not useful anymore. I am going to put this info on the readme since many people seem to get confused.

**Comment by trix0** [comment] 2020-11-23 10:01
> @trix0 this library is outdated. It still uses old google play libs which are not useful anymore. I am going to put this info on the readme since many people seem to get confused.

I see, Do you know any library you could recommend?

Thanks :)

**Comment by nisrulz** [comment] 2020-11-23 12:52
I would suggest you use the [one from Firebase directly](https://developers.google.com/ml-kit/vision/barcode-scanning/android).

When I created this library, the setup was tedious, but I think the new Firebase library is now a good setup to use.

**Comment by nisrulz** [comment] 2021-10-22 00:03
Closing as issue is outdated.

**Closed as completed by nisrulz** 2021-10-22 00:03 UTC
Labels: bug
