### ISSUE TITLE
Restart qreader?

### ISSUE THREAD

**Issue by KalebPortillo** [nisrulz/qreader#15] opened 2016-06-09 16:42 UTC
Hello there, thanks for this great QR reader!

I wonder if its possible to restart the qreader object after call .stop() on it.

For example:
On the onDetect listener, after I detect something, I show a Dialog and call qreader.stop()

```
qrEader = new QREader.Builder(this, surfaceView, new QRDataListener() {
            @Override public void onDetected(final String data) {
                Log.d("QREader", "Value : " + data);
                surfaceView.post(new Runnable() {
                    @Override public void run() {
                        showDialog(data);
                    }
                });
            qrEader.stop();               <------------------------------------- HERE
            }
        }).build();

        qrEader.init();
```

So when I dismiss my Dialog I call qreader.start() but it doens't read the qrcode anymore

```
    private void showDialog(String qrcode) {
        AlertDialog.Builder builder = new AlertDialog.Builder(MainActivity.this);
        builder.setTitle("Confirmar convidado?");
        builder.setMessage(qrcode);

        String positiveText = getString(android.R.string.ok);
        builder.setPositiveButton(positiveText,
                new DialogInterface.OnClickListener() {
                    @Override
                    public void onClick(DialogInterface dialog, int which) {
                        System.out.println("OK");
                        surfaceView.post(new Runnable() {
                            @Override public void run() {
                                qrEader.start();      <------------------------- HERE
                            }
                        });

                    }
                });

        String negativeText = getString(android.R.string.cancel);
        builder.setNegativeButton(negativeText,
                new DialogInterface.OnClickListener() {
                    @Override
                    public void onClick(DialogInterface dialog, int which) {
                        System.out.println("CANCEL");

                        qrEader.start();       <-------------------------------- HERE
                    }
                });

        AlertDialog dialog = builder.create();

        dialog.show();
    }
```

**Comment by nisrulz** [comment] 2016-06-11 07:56
@KalebPortillo I will try and update you by tonight.

**Comment by KalebPortillo** [comment] 2016-06-21 12:11
Any news @nisrulz?

**Comment by nisrulz** [comment] 2016-06-21 12:52
@KalebPortillo I do see your problem here , but I haven't figured out a way to restart the barcode reading once you call stop on it. The behaviour as intended should be that it should start reading QR code but it doesnot. I will update you if I figure out the anomaly.

**Comment by KalebPortillo** [comment] 2016-06-21 13:16
@nisrulz Thanks for your time,
Meanwhile I'm just using a true/false flag wrapping the onDetect method.

**Comment by nefadbr** [comment] 2016-06-27 14:54
+1, having the same problem.

**Comment by nisrulz** [comment] 2016-06-27 14:57
Guys, I haven't got time to fix it lately but I will update it within this week. Meanwhile if anyone else get a change to take a dig at it , then please send a PR.

**Comment by nisrulz** [comment] 2016-09-27 09:07
@punksta provided a fix which is merged into the `develop` branch and should be released soon. Closing this.

**Closed by nisrulz** 2016-09-27 09:07 UTC
